tempo_tailscale_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37666564373339356236613039366466313330623333343535343564643666623762363234646233
          3233666661633963306536633962366262333931653661610a313266313138336633303964663234
          63653539393433336363633262393863366534306562306530383564613337326534623334613939
          3332343530313466650a653034656531613966313865343935633162646463346132356461363163
          62616334623930343263386239613030356233386435636233363764393934663765663635323662
          61626332646430323666346239303061353963393636353838313630356261623235663333623335
          653338326565346661303265346462643738

tempo_github_token: !vault |
          $ANSIBLE_VAULT;1.2;AES256;vault
          63363865313233626633353331366339363964653535363839316635663532373930376265326635
          6566363965636131633337386562363762396630383037370a666364326630303836343332393637
          37383632343833653062663037316564346431326637333938616238653965316165633638356138
          6136646339303838350a376165373630656132323765333637366430386139616331353036623264
          35396336383130336264343834643636336438613434363532363033383338636433653938333739
          35396265613761623466323431623833396534663239376363316564626364613464313837373064
          66613639383230353462613965666535333962366532656535316263353332313064626431373366
          32326536343736366361346466633765313463356562326136616163616536316632613230356431
          6438

tempo_grafana_api_token: !vault |
          $ANSIBLE_VAULT;1.2;AES256;vault
          65366634323038333232616335303733373965663036303130393663636362386566636232663735
          3233663930616338373238663335663238346437313336370a393530663631373031643132323839
          63643232343337393561636232353230376230323161313937386235633633653966336365623931
          6366626139323763320a313038356137353932303638353761343166623831353138383466613339
          65323265666535353664353365323063373337666231373636353464306364306536633236313964
          35313266636639663263356331323763646636343764643838626263376263626633643539623739
          39396430343565353330356139623835313233616435386566303534313062323761613538613034
          32386539323036333236343361633664636232353761616432366663366563613933303562366432
          39623631306166643039653963303765363937356262643065366532653137326431626635353864
          38333931346439326332623431333937356362656234656633643538633236306339396230366234
          31356132663964353233653332343138373238336231633139643965306235393864623262626432
          36356434303465663932623533333837663638326435623234386661623564396639303965616332
          3464


tempo_download_url: "https://api.github.com/repos/tempoxyz/tempo/actions/artifacts/3641329256/zip"
tempo_chain_id: "reth-malachite-testnet"
